version: "3"
services: 
  database:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: template 
  application:
    build: .
    command: npm start
    volumes: 
      - ".:/usr/app"
    
    ports: 
      - "3333:3333"
    links:
      - database
    environment: 
      NODE_ENV: development
      ORIGIN: "*"
      PORT: 3333
      HOST: 0.0.0.0
  
      APP_SECRET: templatesecret
      
      DB_HOST: database
      DB_USER: postgres
      DB_PASS: docker
      DB_NAME: template
